# Data Cleaning

In [11]:
import pandas as pd
data = pd.read_csv("tested.csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [13]:
data[data["PassengerId"] == 892].iloc[: , 1:]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q

# Pclass refers passenger class

1 = First Class (Rich)

2 = Second Class

3 = Third Class (Lower)

## SibSp Column 
     
     "Sibling / Spouse"

     Kitne bhai-behen ya husband/wife saath me the.

## Parch
     
     "Parent / Children"

     Kitne parents ya bachche saath me the.

## Embarked
  
     C = Cherbourg

     Q = Queenstown

     S = Southampton

In [3]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [4]:
data["Pclass"].unique()

array([3, 2, 1], dtype=int64)

# How to delete a column

In [5]:
data.drop(columns= ["PassengerId"] , inplace=True)

# backward filling and forward filling

  ## bfill() fills empty values with the value that comes after them.
        
        If a value is missing, it takes the next value (below it) and puts it there.
        Simple :
               Look down and copy the next value.

  ## ffill() fills empty values with the value that comes before them.
        
        If a value is missing, it takes the previous value (above it) and puts it there.
        Simple word:
                Look up and copy the previous value.


        axis=0 → column-wise (top to bottom)

        axis=1 → row-wise (left to right)

In [6]:
data.bfill()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,B45,Q
1,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,B45,S
2,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,B45,Q
3,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,B45,S
4,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,B45,S
...,...,...,...,...,...,...,...,...,...,...,...
413,0,3,"Spector, Mr. Woolf",male,39.0,0,0,A.5. 3236,8.0500,C105,S
414,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C


   ## Mode 
       Mode is the value that appears the most. 
       Numbers:
            2, 4, 4, 5, 6

       Here 4 appears two times (more than others).
       So,

           Mode = 4

    
  ## How to find mode  in column 

        data["ColumnName"].mode() then put in fillna()

In [7]:
data["Sex"].fillna(data["Sex"].mode()[0], inplace= True)

C:\Users\Vishal\AppData\Local\Temp\ipykernel_26576\3759912073.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Sex"].fillna(data["Sex"].mode()[0], inplace= True)

# How to select a specific type of column.

 ## To get a specific type of column use :

     data.select_dtypes(include= "object")

 ## To get columns name of specific type of data use :
     
     data.select_dtypes(include = "object").columns

In [8]:
data.select_dtypes(include= "object").isnull().sum()

Name          0
Sex           0
Ticket        0
Cabin       327
Embarked      0
dtype: int64

# How to apply mode on mutliple columns

In [9]:
for i in data.select_dtypes(include="object").columns:
    data[i].fillna(data[i].mode()[0])

In [10]:
data.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age          86
SibSp         0
Parch         0
Ticket        0
Fare          1
Cabin       327
Embarked      0
dtype: int64

# Simple Imputer

In [16]:
from sklearn.impute import SimpleImputer

si = SimpleImputer(strategy="mean")

ar = si.fit_transform(data[["Age"]])
ar

array([[34.5       ],
       [47.        ],
       [62.        ],
       [27.        ],
       [22.        ],
       [14.        ],
       [30.        ],
       [26.        ],
       [18.        ],
       [21.        ],
       [30.27259036],
       [46.        ],
       [23.        ],
       [63.        ],
       [47.        ],
       [24.        ],
       [35.        ],
       [21.        ],
       [27.        ],
       [45.        ],
       [55.        ],
       [ 9.        ],
       [30.27259036],
       [21.        ],
       [48.        ],
       [50.        ],
       [22.        ],
       [22.5       ],
       [41.        ],
       [30.27259036],
       [50.        ],
       [24.        ],
       [33.        ],
       [30.27259036],
       [30.        ],
       [18.5       ],
       [30.27259036],
       [21.        ],
       [25.        ],
       [30.27259036],
       [39.        ],
       [30.27259036],
       [41.        ],
       [30.        ],
       [45.        ],
       [25.        ],
       [45.        ],
       [30.27259036],
       [60.        ],
       [36.        ],
       [24.        ],
       [27.        ],
       [20.        ],
       [28.        ],
       [30.27259036],
       [10.        ],
       [35.        ],
       [25.        ],
       [30.27259036],
       [36.        ],
       [17.        ],
       [32.        ],
       [18.        ],
       [22.        ],
       [13.        ],
       [30.27259036],
       [18.        ],
       [47.        ],
       [31.        ],
       [60.        ],
       [24.        ],
       [21.        ],
       [29.        ],
       [28.5       ],
       [35.        ],
       [32.5       ],
       [30.27259036],
       [55.        ],
       [30.        ],
       [24.        ],
       [ 6.        ],
       [67.        ],
       [49.        ],
       [30.27259036],
       [30.27259036],
       [30.27259036],
       [27.        ],
       [18.        ],
       [30.27259036],
       [ 2.        ],
       [22.        ],
       [30.27259036],
       [27.        ],
       [30.27259036],
       [25.        ],
       [25.        ],
       [76.        ],
       [29.        ],
       [20.        ],
       [33.        ],
       [43.        ],
       [27.        ],
       [30.27259036],
       [26.        ],
       [16.        ],
       [28.        ],
       [21.        ],
       [30.27259036],
       [30.27259036],
       [18.5       ],
       [41.        ],
       [30.27259036],
       [36.        ],
       [18.5       ],
       [63.        ],
       [18.        ],
       [30.27259036],
       [ 1.        ],
       [36.        ],
       [29.        ],
       [12.        ],
       [30.27259036],
       [35.        ],
       [28.        ],
       [30.27259036],
       [17.        ],
       [22.        ],
       [30.27259036],
       [42.        ],
       [24.        ],
       [32.        ],
       [53.        ],
       [30.27259036],
       [30.27259036],
       [43.        ],
       [24.        ],
       [26.5       ],
       [26.        ],
       [23.        ],
       [40.        ],
       [10.        ],
       [33.        ],
       [61.        ],
       [28.        ],
       [42.        ],
       [31.        ],
       [30.27259036],
       [22.        ],
       [30.27259036],
       [30.        ],
       [23.        ],
       [30.27259036],
       [60.5       ],
       [36.        ],
       [13.        ],
       [24.        ],
       [29.        ],
       [23.        ],
       [42.        ],
       [26.        ],
       [30.27259036],
       [ 7.        ],
       [26.        ],
       [30.27259036],
       [41.        ],
       [26.        ],
       [48.        ],
       [18.        ],
       [30.27259036],
       [22.        ],
       [30.27259036],
       [27.        ],
       [23.        ],
       [30.27259036],
       [40.        ],
       [15.        ],
       [20.        ],
       [54.        ],
       [36.        ],
       [64.        ],
       [30.        ],
       [37.        ],
       [18.        ],
       [30.27259036],
       [27.        ],
       [40.        ],
       [21.        ],
       [17.        ],
       [30.27259036],
       [40.        ],
       [34.        ],
       [30.27259036],
       [11.5       ],
       [61.        ],
       [ 8.        ],
       [33.        ],
       [ 6.        ],
       [18.        ],
       [23.        ],
       [30.27259036],
       [30.27259036],
       [ 0.33      ],
       [47.        ],
       [ 8.        ],
       [25.        ],
       [30.27259036],
       [35.        ],
       [24.        ],
       [33.        ],
       [25.        ],
       [32.        ],
       [30.27259036],
       [17.        ],
       [60.        ],
       [38.        ],
       [42.        ],
       [30.27259036],
       [57.        ],
       [50.        ],
       [30.27259036],
       [30.        ],
       [21.        ],
       [22.        ],
       [21.        ],
       [53.        ],
       [30.27259036],
       [23.        ],
       [30.27259036],
       [40.5       ],
       [36.        ],
       [14.        ],
       [21.        ],
       [21.        ],
       [30.27259036],
       [39.        ],
       [20.        ],
       [64.        ],
       [20.        ],
       [18.        ],
       [48.        ],
       [55.        ],
       [45.        ],
       [45.        ],
       [30.27259036],
       [30.27259036],
       [41.        ],
       [22.        ],
       [42.        ],
       [29.        ],
       [30.27259036],
       [ 0.92      ],
       [20.        ],
       [27.        ],
       [24.        ],
       [32.5       ],
       [30.27259036],
       [30.27259036],
       [28.        ],
       [19.        ],
       [21.        ],
       [36.5       ],
       [21.        ],
       [29.        ],
       [ 1.        ],
       [30.        ],
       [30.27259036],
       [30.27259036],
       [30.27259036],
       [30.27259036],
       [17.        ],
       [46.        ],
       [30.27259036],
       [26.        ],
       [30.27259036],
       [30.27259036],
       [20.        ],
       [28.        ],
       [40.        ],
       [30.        ],
       [22.        ],
       [23.        ],
       [ 0.75      ],
       [30.27259036],
       [ 9.        ],
       [ 2.        ],
       [36.        ],
       [30.27259036],
       [24.        ],
       [30.27259036],
       [30.27259036],
       [30.27259036],
       [30.        ],
       [30.27259036],
       [53.        ],
       [36.        ],
       [26.        ],
       [ 1.        ],
       [30.27259036],
       [30.        ],
       [29.        ],
       [32.        ],
       [30.27259036],
       [43.        ],
       [24.        ],
       [30.27259036],
       [64.        ],
       [30.        ],
       [ 0.83      ],
       [55.        ],
       [45.        ],
       [18.        ],
       [22.        ],
       [30.27259036],
       [37.        ],
       [55.        ],
       [17.        ],
       [57.        ],
       [19.        ],
       [27.        ],
       [22.        ],
       [26.        ],
       [25.        ],
       [26.        ],
       [33.        ],
       [39.        ],
       [23.        ],
       [12.        ],
       [46.        ],
       [29.        ],
       [21.        ],
       [48.        ],
       [39.        ],
       [30.27259036],
       [19.        ],
       [27.        ],
       [30.        ],
       [32.        ],
       [39.        ],
       [25.        ],
       [30.27259036],
       [18.        ],
       [32.        ],
       [30.27259036],
       [58.        ],
       [30.27259036],
       [16.        ],
       [26.        ],
       [38.        ],
       [24.        ],
       [31.        ],
       [45.        ],
       [25.        ],
       [18.        ],
       [49.        ],
       [ 0.17      ],
       [50.        ],
       [59.        ],
       [30.27259036],
       [30.27259036],
       [30.        ],
       [14.5       ],
       [24.        ],
       [31.        ],
       [27.        ],
       [25.        ],
       [30.27259036],
       [30.27259036],
       [22.        ],
       [45.        ],
       [29.        ],
       [21.        ],
       [31.        ],
       [49.        ],
       [44.        ],
       [54.        ],
       [45.        ],
       [22.        ],
       [21.        ],
       [55.        ],
       [ 5.        ],
       [30.27259036],
       [26.        ],
       [30.27259036],
       [19.        ],
       [30.27259036],
       [24.        ],
       [24.        ],
       [57.        ],
       [21.        ],
       [ 6.        ],
       [23.        ],
       [51.        ],
       [13.        ],
       [47.        ],
       [29.        ],
       [18.        ],
       [24.        ],
       [48.        ],
       [22.        ],
       [31.        ],
       [30.        ],
       [38.        ],
       [22.        ],
       [17.        ],
       [43.        ],
       [20.        ],
       [23.        ],
       [50.        ],
       [30.27259036],
       [ 3.        ],
       [30.27259036],
       [37.        ],
       [28.        ],
       [30.27259036],
       [39.        ],
       [38.5       ],
       [30.27259036],
       [30.27259036]])

# Outlier 

     Outliers are data points that significantly deviate from the overall pattern of a dataset.

     
     1. They can appear as unusually high or low values compared to the rest of the data. 
     2. Can affect mean, variance, and model performance.
     3. Detected using statistical and visual methods.
     4. Important to analyze before removing or treating them

# Why Outlier Occur 
    
  ## Data Entry Errors:
       When we enter data manually, typing mistakes can happen.
       For example, writing age 20000 instead of 20. This creates a wrong value.

  ## Measurement Errors
       If a machine or measuring instrument is not working properly, it can give incorrect readings.
       For example, a faulty thermometer may show very high or very low temperature.

  ## Intentional Outliers
       Sometimes people change data on purpose.
       This happens in cases like fraud or data manipulation.
       
  ## Data Processing Errors
       Mistakes can happen while collecting, cleaning, or transforming data.
       For example, applying the wrong formula or mixing up columns.

In [12]:
import pandas as pd

data_clean = pd.read_csv("tested.csv")

In [14]:
data_clean.drop(columns= ["PassengerId" , "Cabin"] , inplace= True)

In [ ]:
data_clean

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...
413,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,S
414,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C
415,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S
416,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,S
417,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,C

In [17]:
data_clean.dropna(subset=["Fare"], inplace=True)

In [18]:
data_clean.isnull().sum()

Survived     0
Pclass       0
Name         0
Sex          0
Age         86
SibSp        0
Parch        0
Ticket       0
Fare         0
Embarked     0
dtype: int64

In [20]:
data_clean.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  417.000000  417.000000  331.000000  417.000000  417.000000  417.000000
mean     0.364508    2.263789   30.181269    0.448441    0.393285   35.627188
std      0.481870    0.842077   14.104573    0.897568    0.982419   55.907576
min      0.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   21.000000    0.000000    0.000000    7.895800
50%      0.000000    3.000000   27.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   39.000000    1.000000    0.000000   31.500000
max      1.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [23]:
data_clean["Age"].mode()

0    21.0
1    24.0
Name: Age, dtype: float64