# Multiple Linear Regression Project

## When Do We Use Multiple Linear Regression?

    Multiple Linear Regression is used when we want to predict a continuous numerical value using two or more independent variables.
    For example, in house price prediction, the price of a house depends on several factors such as:

    House size
    Number of bedrooms
    Age of the house
    Distance from the city

## The model finds a best-fit hyperplane that minimizes the error and gives us the predicted value.

    Common Examples:

    House price prediction
    Salary prediction
    Sales forecasting
    Temperature prediction

    When Should We NOT Use Multiple Linear Regression?
    We should not use Multiple Linear Regression when the target variable is categorical, such as:

        Yes / No
        Pass / Fail
        Buy / Not Buy

In [1]:
import pandas as pd

data = pd.read_csv("house_data_large.csv")

x = data.iloc[: , :-1].values
y = data.iloc[: , -1].values

data

    HouseSize  Bedrooms  Age  DistanceFromCity   Price
0        2109         2    1                13   71.81
1        1257         3   24                 3   43.35
2        1916         2   19                 8   54.76
3         991         3    8                10   34.26
4        1949         3   23                12   58.57
5        1659         3   15                11   50.64
6         813         3   23                 8   15.52
7        1118         3   25                 7   25.24
8        1578         2   12                15   39.46
9        1341         2   24                 9   31.30
10       1575         2   18                 6   52.89
11       2066         4   19                 5   81.99
12        893         3   25                 6   26.57
13       1276         2   13                 6   41.17
14       1547         3   12                 7   53.88
15       1346         2   20                12   26.55
16       2293         3    6                 9   87.21
17       2110         3   22                 7   74.73
18       2389         2    8                15   71.98
19       1446         5    9                 3   68.25
20       1961         4    7                12   74.83
21       2116         5    5                 6   93.04
22       2325         4   24                11   76.58
23       1995         5   12                 5   92.67
24       1083         5    3                14   40.39
25       1024         3   21                 4   36.08
26       1664         2   13                 8   55.12
27       1758         4   18                15   57.84
28       2193         2   22                10   67.63
29       2374         4    4                 6  102.11
30       1729         2   24                13   38.09
31       1825         3   17                 3   73.61
32       1411         3    5                 7   59.57
33       1904         2   20                 7   59.55
34       1029         4   10                 5   41.24
35       1961         2    3                13   66.40
36        941         3    5                12   30.39
37       1925         3    9                10   73.52
38       1666         3   18                14   48.54
39       1211         4   13                12   41.54
40       1697         5    4                 5   79.43
41       1492         2   19                10   36.78
42       1251         2    3                13   39.45
43       1268         2    2                15   34.92
44       1852         3    9                12   63.73
45       1904         3   24                11   56.22
46       1297         5   14                 5   54.12
47       2149         5   12                 8   88.47
48       2293         2   22                12   70.96
49       1001         2   13                13   18.53

In [2]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size= 0.2 , random_state=10)

In [3]:
from sklearn.linear_model import LinearRegression

lg = LinearRegression()

lg.fit(x_train , y_train)

LinearRegression()

In [4]:
lg.predict(x_test)

array([68.67169492, 86.83869327, 62.62973733, 35.82085206, 88.40444944,
       72.99025678, 31.61555744, 42.1186736 , 30.87427956, 18.25940814])

In [5]:
x_test , y_test

(array([[1925,    3,    9,   10],
        [1995,    5,   12,    5],
        [1852,    3,    9,   12],
        [1251,    2,    3,   13],
        [2149,    5,   12,    8],
        [1961,    4,    7,   12],
        [ 991,    3,    8,   10],
        [1729,    2,   24,   13],
        [1118,    3,   25,    7],
        [ 813,    3,   23,    8]], dtype=int64),
 array([73.52, 92.67, 63.73, 39.45, 88.47, 74.83, 34.26, 38.09, 25.24,
        15.52]))

In [6]:
lg.score(x_test , y_test)

0.9795986094199413

Degree means the highest total power of all features in a term should not be greater than the given degree, and we multiply features only until their total power reaches that degree

In [7]:
import pandas as pd

poly_data = pd.read_csv("poly_data.csv")
poly_data.head()

   Size_sqft  Age  Luxury_Score  Quality Location        Price
0       1360   29             7   Medium    Urban  148311.6691
1       1794   21             9     High    Urban  147297.2754
2       1630   23             7      Low    Urban  216237.7891
3       1595    1             5  Premium    Rural  394071.5557
4       2138    3             7      Low    Rural  409664.9337

In [8]:
x = poly_data.iloc[: , :-1]
y = poly_data.iloc[: , -1]

In [9]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size=0.2 , random_state=90)

In [10]:
poly_data["Quality"].unique() , poly_data["Location"].unique()

(array(['Medium', 'High', 'Low', 'Premium'], dtype=object),
 array(['Urban', 'Rural', 'Suburban'], dtype=object))

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder , OneHotEncoder

categories = [["Low","Medium","High","Premium"]]

ct = ColumnTransformer(
    transformers= [
        ("ord" , OrdinalEncoder(categories=categories) , ["Quality"]),
        ("ohe" , OneHotEncoder(drop= "first" , sparse_output=False), ["Location"])
    ],
    remainder="passthrough"
)

ct.fit(x_train)

x_train_final = ct.transform(x_train)
x_test_final = ct.transform(x_test)

In [12]:
from sklearn.preprocessing import PolynomialFeatures

pf = PolynomialFeatures(degree= 2)

pf.fit(x_train_final)

x_train_poly = pf.transform(x_train_final)
x_test_poly = pf.transform(x_test_final)

In [13]:
from sklearn.linear_model import LinearRegression

lg = LinearRegression()

lg.fit(x_train_poly , y_train)

LinearRegression()

In [14]:
lg.score(x_test_poly , y_test)

0.8460442049766961